version: '3.8'

services:
  api:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "3008:3008" 
    volumes: 
      - ./backend:/app
    env_file:
      - .env 

  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  
    depends_on:
      - api 
    volumes:
      - ./frontend:/app  
    env_file:
      - .env  
